version: '3.8'

services:
  backend-echo:
    container_name: backend-echo
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /app/echo
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_DB: "NotebookApp"
      POSTGRES_HOST: "postgres"
      GOMAXPROC: 1
    networks:
      - noteappnetwork
    ports:
      - "8081:8081"

  backend-gin:
    container_name: backend-gin
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /app/gin
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_DB: "NotebookApp"
      POSTGRES_HOST: "postgres"
      GOMAXPROC: 1
    networks:
      - noteappnetwork
    ports:
      - "8082:8081"

  backend-chi:
    container_name: backend-chi
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /app/chi
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_DB: "NotebookApp"
      POSTGRES_HOST: "postgres"
      GOMAXPROC: 1
    networks:
      - noteappnetwork
    ports:
      - "8083:8081"

  postgres:
    container_name: postgres_container
    image: bitnami/postgresql:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_DB: "NotebookApp"
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/dbpgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - noteappnetwork
    restart: unless-stopped

  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - noteappnetwork
    restart: unless-stopped  

networks:
  noteappnetwork:
    driver: bridge